name: Check
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
        - '2.7'
        - '2.6'
        - '2.5'
        - '2.4'
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "${{matrix.ruby}}"
      - run: |
          gem install bundler --no-document
          bundle config set without 'tools benchmarks docs'
      - run: bundle install --jobs 4 --retry 3
      - run: bundle exec standardrb
      - run: bundle exec rake